export const tvs = [
    { key: 10759, name: 'action' },
    { key: 16, name: 'animation' },
    { key: 80, name: 'crime' },
    { key: 99, name: 'documentary' },
    { key: 18, name: 'drama' },
    { key: 10751, name: 'family' },
    { key: 36, name: 'history' },
    { key: 10402, name: 'music' },
    { key: 9648, name: 'mystery' },
    { key: 10749, name: 'romance' },
    { key: 37, name: 'western' }
];

export const movies = [
    { key: 28, name: 'action' },
    { key: 12, name: 'adventure' },
    { key: 16, name: 'animation' },
    { key: 80, name: 'crime' },
    { key: 99, name: 'documentary' },
    { key: 18, name: 'drama' },
    { key: 10751, name: 'family' },
    { key: 14, name: 'fantasy' },
    { key: 36, name: 'history' },
    { key: 27, name: 'horror' },
    { key: 10402, name: 'music' },
    { key: 9648, name: 'mystery' },
    { key: 10749, name: 'romance' },
    { key: 878, name: 'science' },
    { key: 53, name: 'thriller' },
    { key: 10752, name: 'war' },
    { key: 37, name: 'western' }
];

export const allGenres = [
    { key: 28, name: 'Action' },
    { key: 10759, name: 'Action' },
    { key: 12, name: 'Adventure' },
    { key: 35, name: 'Comedy' },
    { key: 16, name: 'Animation' },
    { key: 80, name: 'Crime' },
    { key: 99, name: 'Documentary' },
    { key: 18, name: 'Drama' },
    { key: 10751, name: 'Family' },
    { key: 14, name: 'Fantasy' },
    { key: 36, name: 'History' },
    { key: 27, name: 'Horror' },
    { key: 10402, name: 'Music' },
    { key: 9648, name: 'Mystery' },
    { key: 10749, name: 'Romance' },
    { key: 878, name: 'Science Fiction' },
    { key: 10770, name: 'Tv Movie' },
    { key: 53, name: 'Thriller' },
    { key: 10752, name: 'War' },
    { key: 37, name: 'Western' },
    { key: 10762, name: "Kids" },
    { key: 10764, name: "Reality" },
    { key: 10767, name: "Talk" },
    { key: 10768, name: "War & Politics" },
    { key: 10765, name: "Sci-Fi & Fantasy" },
];
